QEMU_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_KITOS_PATH)/../qemu/qemu-9.2.0
# HOST_QEMU_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_KITOS_PATH)/../qemu-host/qemu-9.2.0
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_KITOS_PATH)/../linux/linux-6.12.9
BUSYBOX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_KITOS_PATH)/../busybox/busybox-1.35.0
