QEMU_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_MINISYS_PATH)/../qemu/qemu-9.2.0
LINUX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_MINISYS_PATH)/../linux/linux-6.12.9
BUSYBOX_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_MINISYS_PATH)/../busybox/busybox-1.35.0
